X_ZCAmin, X_ZCAmax = -28.21404101296473, 30.95940075784862
#network_type                        = 'pi'                      # Valid values: 'pi', 'tempens'.
num_classes                         = 10                        # Number of classes.
supervised_ratio                    = 1                         # Rate of labeled data.
rampup_length                       = 80                        # Ramp learning rate and unsupervised loss weight up during first n epochs.
rampdown_length                     = 50                        # Ramp learning rate and Adam beta1 down during last n epochs.
beta1                               = 0.9                       # Default value.
beta2                               = 0.999                     # Default value.
rampdown_beta1_target               = 0.5                       # Target value for Adam beta1 for rampdown.
num_epochs                          = 300                       # Total number of epochs.
minibatch_size                      = 100                       # Number of samples in batch.
noise_stddev                        = 0.15
batch_normalization_momentum        = 0.999                     # Batch normalization momentum.
learning_rate_max                   = 0.003                     # Maximum learning rate.
augment_translation                 = 0.0625                    # Image translation by augment_translation * img_size pixels
unsup_weight_max                    = 100.0                     # Unsupervised loss maximum (w_max in paper). Set to 0.0 -> supervised loss only.
start_epoch                         = 0                         # Which epoch to start training from. For continuing a previously trained network.
load_network_filename               = None                      # Set to load a previously saved network.
no_label                            = -1

# run_desc                            = 'baseline'                # Name the results directory to be created for current run.
# network_type                        = 'pi'                      # Valid values: 'pi', 'tempens'.
# dataset                             = 'svhn'                    # Valid values: 'cifar-10', 'svhn'.
#aux_tinyimg                         = None                      # Valid values: None, 'c100', # for any.
#whiten_inputs                       = 'norm'                    # Valid values: None, 'norm', 'zca'.
#augment_noise_stddev                = 0.15                      # Controls the Gaussian noise added inside network during training.
#augment_mirror                      = False                     # Enable horizontal flip augmentation.
#augment_translation                 = 2                         # Maximum translation distance for augmentation. Must be an integer.
#num_labels                          = 500                       # Total number of labeled inputs (1/10th of this per class). Value 'all' uses all labels.
#corruption_percentage               = 0                         # How big percentage of input labels to corrupt.
#num_epochs                          = 300                       # Number of epochs to train.
#max_unlabeled_per_epoch             = None                      # Set this to use at most n unlabeled inputs per epoch.
#minibatch_size                      = 100                       # Samples per minibatch.
#batch_normalization_momentum        = 0.999                     # Mean-only batch normalization momentum.
#learning_rate_max                   = 0.003                     # Maximum learning rate.
#rampup_length                       = 80                        # Ramp learning rate and unsupervised loss weight up during first n epochs.
#rampdown_length                     = 50                        # Ramp learning rate and Adam beta1 down during last n epochs.
#rampdown_beta1_target               = 0.5                       # Target value for Adam beta1 for rampdown.
#adam_beta1                          = 0.9                       # Default value.
#adam_beta2                          = 0.999                     # Default value.
#adam_epsilon                        = 1e-8                      # Default value.
#prediction_decay                    = 0.6                       # Ensemble prediction decay constant (\alpha in paper).
#unsup_weight_max                    = 100.0                     # Unsupervised loss maximum (w_max in paper). Set to 0.0 -> supervised loss only.
#load_network_filename               = None                      # Set to load a previously saved network.
# start_epoch                         = 0                         # Which epoch to start training from. For continuing a previously trained network.
#cuda_device_number                  = 0                         # Which GPU to use.
#random_seed                         = 1000                      # Randomization seed.
